name: daily-pe-to-google-sheets

on:
  schedule:
    - cron: "30 4 * * *"   # 10:00 AM IST (04:30 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_EMAIL: ${{ secrets.TARGET_SHARE_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: List files
        run: ls -lah

      # - name: Write service account key
      #   run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > /tmp/gcp.json

      - name: Decode service account JSON
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" | base64 -d > /tmp/gcp.json


      - name: DEBUG PRINT JSON (masked)
        run: |
          sed 's/-----BEGIN PRIVATE KEY-----/PRIVATE_KEY_START/g' /tmp/gcp.json \
          | sed 's/-----END PRIVATE KEY-----/PRIVATE_KEY_END/g' \
          | sed 's/[A-Za-z0-9/+]\{20,\}/MASKED/g'

      - name: Upload CSV to Google Sheets
        run: python upload_to_sheets.py
